"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=_m_+ad(7e)02wn9jjk^=eu#s7m3fes4nnb94zxu#g63^i_w++'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'qms',        
    'login_app',
    'rest_framework_simplejwt',      
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
   
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'your_quiz_db_name',         # તમારા MySQL ડેટાબેઝનું નામ
        'USER': 'your_mysql_user',           # તમારા MySQL યુઝરનું નામ
        'PASSWORD': 'your_mysql_password',   # તમારા MySQL પાસવર્ડ
        'HOST': 'localhost',                 # સામાન્ય રીતે 'localhost'
        'PORT': '3306',                      # MySQL નો ડિફોલ્ટ પોર્ટ
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# backend/settings.py (ફાઇલના અંતમાં ગમે ત્યાં ઉમેરો)

# --- CORS SETTINGS ---
CORS_ALLOWED_ORIGINS = [
    # તમારા React/Vite Dev Server નો ડિફોલ્ટ પોર્ટ
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175", 
]

# જો તમે production માં ડિપ્લોય કરો, તો CORS_ALLOW_ALL_ORIGINS = True વાપરવાનું ટાળો
CORS_ALLOW_CREDENTIALS = True # જો તમારે Cookies, Authorization Headers વગેરે મોકલવા હોય

# --- REST FRAMEWORK SETTINGS ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWT Token દ્વારા ઓથેન્ટિકેશન માટે આ ઉમેરો
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # શરૂઆતમાં બધાને પરવાનગી આપો
    )
}
# backend/settings.py (સૌથી નીચે ઉમેરો)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # આને પછીથી કન્ફિગર કરીશું, અત્યારે ફક્ત ઓથેન્ટિકેશન ચેક કરવા માટે
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

# Simple JWT માટેનું કન્ફિગરેશન (વૈકલ્પિક, પરંતુ ભલામણ કરેલ)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # 1 કલાક
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 7 દિવસ
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'તમારી ખૂબ જ ગુપ્ત કી અહીં બદલો', # આ કીને તમારી SECRET_KEY માંથી વાપરી શકાય છે
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# backend/settings.py (સૌથી નીચે, બંને ડિક્શનરી ભેગી કરીને રાખો)

# --- REST FRAMEWORK SETTINGS ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWT Token દ્વારા ઓથેન્ટિકેશન માટે આ ઉમેરો
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # શરૂઆતમાં બધાને પરવાનગી આપો
    )
}

# Simple JWT માટેનું કન્ફિગરેશન
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # SECRET_KEY નો ઉપયોગ કરો
    'AUTH_HEADER_TYPES': ('Bearer',),
}