# Generated by Django 5.2.8 on 2025-12-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
